### ISSUE TITLE
Format der Markdown-Notizen

### ISSUE THREAD

**Issue by speicherwerk** [Mulsch/FestundFlauschig#3]
Hallo, mir ist aufgefallen, dass die Markdown-Notizen nicht dem Standard entsprechen. Aufzählungen benutzen hier einen Punkt, während Markdown entweder einen Strich - oder eine Asterisk * verlangt. Eingerückte Stichpunkte benutzen das kleine O o und die Zeilenendungen sind teilweise sehr komisch (nur CR, ohne LF).

Darf ich fragen, welche Software Du benutzt (ich rate irgendwas auf macOS, vielleicht die Notizen-App?) und ob Du daran interessiert wärst, das Format zu standardisieren. Das könnte gerne ich mit ein bisschen shell-script Magie übernehmen. Es hat meines Erachtens wenig Sinn, Markdown zu benutzen, wenn die Notizen nicht tatsächlich im Markdown-Format sind. Man könnte zum Beispiel auch überlegen ein Markdown Wiki Format zu benutzen, wobei man mit [[Name]] andere Folgen verlinken kann (zum Beispiel [Obsidian](https://obsidian.md/) würde sich dafür hervorragend eignen). Gerne kannst Du auch sagen, falls Du das ganze nicht so verkomplizieren willst und stattdessen einfach weiter Deine (übrigens hervorragende) Arbeit machen willst.

**Comment by Mulsch** [comment]
Moin Malte,
vielen lieben Dank zunächst auch für deine ganze Mühen und die Arbeit, die
du schon jetzt in dieses Repository gesteckt hast. Ich habe deine Nachricht
auf mein Mailpostfach erhalten und antworte direkt per Mail, hoffentlich
klappt das.

Leider bin ich IT-mäßig eher durchschnittlich veranlagt. Alle bisher
hochgeladenen Dateien waren ursprünglich in einem einzigen Word-Dokument
gesammelt, ich habe dann die Folgen im Editor zu einzelnen TXT-Dateien
umgewandelt.
Markdown war mir bis vor einigen Tagen noch kein Begriff, erst durch den
Hinweis eines Kumpels kam ich darauf und begann, die hochgeladenen
TXT-Dateien Stück für Stück in das MD-Format umzuwandeln. Dabei ist mir,
wie du schon richtig festgestellt hast, aufgefallen, dass eingerückte
Stichpunkte als "o" formatiert werden und in der fertigen Version nicht
tatsächlich eingerückt sind. Allerdings ist dies (meines Wissens nach) nur
bei einigen wenigen Sanft & Sorgfältig Folgen der Fall, weswegen ich
glaube, dass dies auch relativ schnell per Hand gefixt werden kann. Falls
du an dieser Stelle mit shell-script zaubern kannst, natürlich umso besser!

Seit kurzer Zeit habe ich mit der Zusammenfassung der Folgen von Fest &
Flauschig begonnen. Dabei arbeite ich direkt in einer neuen MD-Datei in
GitHub, die erste Datei dieser Art ("2016_05_15 - Aufbau West") hast du ja
schon gesehen. Mein Plan war es, das Format dieser Datei als einheitlichen
Standard zu verwenden, sodass auch zukünftige Notizen direkt im Repository
erstellt werden und nicht lokal auf dem PC und erst dann hochgeladen
werden. Sag mir gerne Bescheid, falls das ein schlechter Plan ist.

Was das Wiki angeht, klingt dein Vorschlag definitiv vielversprechend. Ich
kann mir sehr gut vorstellen, wie diese Verlinkungen am Ende funktionieren,
bin aber mit der Umsetzung bislang noch absolut gar nicht vertraut. Da ich
dieses Projekt derzeit allein betreibe und meist nur Zeit für eine Folge
pro Tag habe, könnte das Reinfuchsen in die Thematik ein wenig Zeit in
Anspruch nehmen. Auch GitHub ist für mich völliges Neuland, daher bin ich
mir (noch) nicht sicher, inwiefern ich anderen Nutzern welche Rechte geben
kann und wie genau alles zusammenhängt (freue mich dementsprechend riesig
über jegliche Unterstützung).

Liebe Grüße!

Am So., 5. Nov. 2023 um 19:47 Uhr schrieb Malte Dostal <
***@***.***>:

**Comment by speicherwerk** [comment]
Jo, per Mail antworten klappt supi.

Ah ja das ergibt auch Sinn, da war meine macOS + iNotes Vermutung ja ganz falsch ;)

Ja das stimmt, die o-Unterpunkte sind mir auch nur bei einzelnen Dateien aufgefallen, das kann man freilich manuell fixen.

Die angesprochenen Zeilenenden habe ich schon per script bei mir gefixt, kann ich gleich noch eine pull-request öffnen.

Jo ich denke die Dateien direkt auf GitHub zu erstellen ist gar nicht schlecht und macht es sozusagen "laiensicher", da kannst du kaum was falsch machen (sonst kann git schnell ne bitch werden wenn man nicht weiß was man tut).

Das mit den Rechten kann gerne so bleiben wie es ist. Dir gehört das Projekt und andere können wie ich per pull-request Änderungen vorschlagen.

Ich finde es übrigens fantastisch, dass Die Dateinamen mit ISO-orientierten Daten anfangen, dann werden sie immer chronologisch sortiert. Überhaupt finde ich das Projekt super und hatte mir so was schon mal speziell für FuF gewünscht, vor allem damit man nach Folgen gezielt suchen kann.
