### ISSUE TITLE
Folgenliste.md ist ca. ab dem 19.04.2020 um -1 Tag verschoben.

### ISSUE THREAD

**Issue by ste404** [Mulsch/FestundFlauschig#8]
In [FestundFlauschig]/[Folgen]/[Fest & Flauschig]/Folgenliste.md ist das Datum der Folgen ca. ab dem 19.04.2020 um jeweils einen Tag nach vorne verschoben.

Also, die Sonntagsfolgen haben das Samstagsdatum und die Mittwochsfolgen das Datum vom Dienstag.

Ich weiß nicht, wie man das am besten clever behebt, aber da das (mindestens ab dem 19.04.2020) ein systematischer Fehler zu sein scheint gibt es evtl. einen eleganten Weg.

PS; Man könnte auch im Sinne der Konsistenz andenken sich bei den Verzeichnisnamen entweder für "FestundFlauschig" oder für die Schreibweise "Fest & Flauschig" zu entscheiden. Geht aber auch so. :-)

**Comment by Mulsch** [comment]
Top, danke für den Hinweis, Daten der Folgen müssten hoffentlich soweit gefixt sein. Werde morgen die Liste ggf. noch bis zu den aktuellen Folgen aktualisieren.

Das mit den Verzeichnisnamen kann ich nachvollziehen, kann ich allerdings nicht mehr ändern (soweit ich weiß), weil das der Name fürs gesamte Repository ist.

Vielen lieben Dank übrigens auch für deinen ersten Pull Request, hat mir sehr gut gefallen! Gerne weiter so :)
